<a href="https://colab.research.google.com/github/sdcsuzana/alura-plus/blob/main/Conhe%C3%A7a_o_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [14]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [17]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [18]:
df.shape

(133349, 11)

In [19]:
linhas,colunas = df.shape[0], df.shape[1]
print("linhas:", linhas)
print("colunas:", colunas)

linhas: 133349
colunas: 11

In [35]:
df.columns

Index(['ano', 'senoridade', 'contrato', 'cargo', 'salario', 'moeda', 'usd',
       'residencia', 'remoto', 'empresa', 'tamanho_empresa'],
      dtype='object')

In [37]:
df["senoridade"].value_counts()

senoridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [38]:
df["contrato"].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [39]:
df["remoto"].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [40]:
df["tamanho_empresa"].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

/tmp/ipython-input-1529184918.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['contrato'].replace(contract_translations, inplace=True)

contrato
Integral      132563
Contrato         394
Parcial          376
Freelancer        16
Name: count, dtype: int64

/tmp/ipython-input-4034762817.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['tamanho_empresa'].replace(company_size_translations, inplace=True)

tamanho_empresa
Média      129561
Grande       3574
Pequena       214
Name: count, dtype: int64

In [44]:
# Create a dictionary to translate the categories in 'remoto'
remote_translations = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

# Replace the values in the 'remoto' column with their Portuguese translations
df['remoto'].replace(remote_translations, inplace=True)

# Display the updated value counts for the 'remoto' column
display(df['remoto'].value_counts())

/tmp/ipython-input-266828730.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['remoto'].replace(remote_translations, inplace=True)

remoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [45]:
df.head()

,ano,senoridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Média
1,2025.0,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Média
2,2025.0,Intermediário,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Média
3,2025.0,Intermediário,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Média
4,2025.0,Entrada,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Média

In [46]:
df.describe(include="object")

,senoridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Integral,Data Scientist,USD,US,Presencial,US,Média
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [47]:
df.describe()

                 ano       salario            usd
count  133339.000000  1.333490e+05  133349.000000
mean     2024.358770  1.632833e+05  157617.272098
std         0.680627  2.173860e+05   74288.363097
min      2020.000000  1.400000e+04   15000.000000
25%      2024.000000  1.060200e+05  106000.000000
50%      2024.000000  1.470000e+05  146206.000000
75%      2025.000000  1.990000e+05  198000.000000
max      2025.000000  3.040000e+07  800000.000000

In [48]:
df.isnull()

,ano,senoridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [49]:
df.head()

,ano,senoridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Média
1,2025.0,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Média
2,2025.0,Intermediário,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Média
3,2025.0,Intermediário,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Média
4,2025.0,Entrada,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Média

In [51]:
df.isnull().sum()

ano                10
senoridade          0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [52]:
df["ano"].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [53]:
df[df.isnull().any(axis=1)]

,ano,senoridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,Senior,Integral,Product Manager,184500,USD,184500,US,Presencial,US,Média
59692,NaN,Intermediário,Integral,Engineer,110000,USD,110000,DE,Presencial,DE,Média
59710,NaN,Entrada,Integral,Data Scientist,208800,USD,208800,US,Presencial,US,Média
59759,NaN,Senior,Integral,Software Engineer,135000,USD,135000,US,Presencial,US,Média
59789,NaN,Senior,Integral,Engineer,112000,USD,112000,US,Presencial,US,Média
131000,NaN,Senior,Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,Média
131006,NaN,Senior,Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,Média
133054,NaN,Entrada,Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,Grande
133281,NaN,Intermediário,Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,Grande
133317,NaN,Intermediário,Integral,Data Scientist,130000,USD,130000,US,Híbrido,US,Grande

In [68]:
import numpy as np

df_salarios = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carlos", "Daniele"],
    "salario": [4000, np.nan, 5000, np.nan]
})

df_salarios["salario_media"] = df_salarios["salario"].fillna(df_salarios["salario"].mean().round(2))
df_salarios

      nome  salario  salario_media
0      Ana   4000.0         4000.0
1    Bruno      NaN         4500.0
2   Carlos   5000.0         5000.0
3  Daniele      NaN         4500.0